version: 0.2

artifacts:
  files:
    - '**/*' # Adjust the path as needed
  base-directory: 'dist' # Specify the base directory of your build artifacts
  name: 'output-${BUILD_ID}' # Optional: specify artifact name with placeholders
  encryption-disabled: false # Optional: specify whether encryption is disabled
  s3:
    bucket: alphafetus-testbucket
    path: CodeBuildOutput/ # Optional: specify a path in the S3 bucket
