version: 0.2

phases:
  install:
    commands:
      - echo Installing with npm...
      - npm install
  build:
    commands:
      - echo Building with npm...
      - npm run build

artifacts:
  files:
    - "*/*"
    - "dist/bundles/*"
  base-directory: "dist"
