version: 0.2

phases:
  install:
    commands:
      - echo Finding git branch...
      - git rev-parse --abbrev-ref HEAD
      - echo Installing with npm...
      - npm install
  build:
    commands:
      - echo Building with npm...
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  s3:
    bucket: "alphafetus-testbucket"
    path: WebsiteBuildOutput/
    canned_acl: "public_read"
