name: AWS Lambda Deployment

on:
  workflow_dispatch:

jobs:
  aws-lambda:
    runs-on: ubuntu-latest
    environment: amazon-s3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.CODEBUILDPUBLIC }}
          aws-secret-access-key: ${{ secrets.CODEBUILDPRIVATE }}

      - name: Zip Lambda function
        run: |
          cd src/lambdaFunctions
          zip -r lambda.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name testDeploy --zip-file fileb://lambda.zip
