name: AWS Lambda Deployment

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  aws-lambda:
    runs-on: ubuntu-latest
    environment: amazon-lambda

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.CODEBUILDPUBLIC }}
          aws-secret-access-key: ${{ secrets.CODEBUILDPRIVATE }}

      - name: Deploy to AWS Lambda
        run: |
          make lambda
