name: AWS CodeBuild Deployment

on:
  workflow_dispatch: 
  release:
    types: [published]

jobs:
  aws-codebuild:
    runs-on: ubuntu-latest
    environment: amazon-s3

    steps:
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.CODEBUILDPUBLIC }}
          aws-secret-access-key: ${{ secrets.CODEBUILDPRIVATE }}
          
    
      - name: Build on AWS CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: WebsiteBuildGithub
