name: Build with AWS SAM

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install global dependencies
        run: |
          npm run installGlobals

      - name: Build AWS SAM Template
        run: |
          sam build